# see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: friday

  # Maintain dependencies for Bundler
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: wednesday
